services:
  test:
    container_name: projects-ia-email-classifica-test
    build: .
    command: test
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "9000:8000"

  web:
    container_name: projects-ia-email-classifica
    build: .
    command: runserver
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "9000:8000"
    environment:
      - PYTHONPATH=/app
